"""add review table

Revision ID: a028f50183e8
Revises: 27812ef085c8
Create Date: 2026-03-31 16:08:20.321327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a028f50183e8'
down_revision: Union[str, Sequence[str], None] = '27812ef085c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('reviews', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###
